services:
  - type: web
    name: local-event-project
    env: python
    branch: main
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn localeventproject.wsgi:application
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: localeventproject.settings
